### ISSUE TITLE
Any guidance on using the NPM package as a project dependency?

### ISSUE THREAD

**Issue by mpas** [bats-core/bats-core#1019]
I am trying to use bats as a project dependency to run my bats tests using Npm/Yarn but I seem to hit a wall.

Using a fresh node 22 installation:

1. Enable Corepack
2. Update Yarn to 4.5.x
3. Add bats a development dependency (`yarn add bats -D`)
4. Run bats for my tests results in the following error..

```
<user path>/.yarn/berry/cache/bats-npm-1.11.0-09f34953f9-10c0.zip/node_modules/bats/bin/bats:3
set -euo pipefail
         ^^^^^^^^

SyntaxError: Unexpected identifier 'pipefail'
    at wrapSafe (node:internal/modules/cjs/loader:1469:18)
    at Module._compile (node:internal/modules/cjs/loader:1491:20)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/Users/mpas/Development/philips/terragrunt-plan-action/.pnp.cjs:5686:33)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1128:12)
    at require$$0.Module._load (/Users/mpas/Development/philips/terragrunt-plan-action/.pnp.cjs:5534:31)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)

Node.js v22.11.0
```

**Comment by martin-schulze-vireso** [comment]
I am not familiar with node/npm myself, so I can only guess from the output that it tries to run the bats executable via a js interpreter?

I don't see how bats is invoked in your example. Is this the first line? What is that trailing `:3` about?
